
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "INIT PAL SIMB TOKENGramatica : LexLex : INIT PAL ListList : Literals Ignore TokensLiterals : INIT PAL '=' SIMBIgnore : INIT PAL '=' SIMBTokens : INIT PAL '=' ListTokensListTokens : '[' TOKEN ListTokens ']'ListTokens : ',' TOKENListTokens : "
    
_lr_action_items = {'INIT':([0,4,7,9,15,19,],[3,5,10,13,-4,-5,]),'$end':([1,2,6,12,18,20,24,26,],[0,-1,-2,-3,-9,-6,-8,-7,]),'PAL':([3,5,10,13,],[4,8,14,16,]),'=':([8,14,16,],[11,17,18,]),'SIMB':([11,17,],[15,19,]),'[':([18,23,],[21,21,]),',':([18,23,],[22,22,]),'TOKEN':([21,22,],[23,24,]),']':([23,24,25,26,],[-9,-8,26,-7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Gramatica':([0,],[1,]),'Lex':([0,],[2,]),'List':([4,],[6,]),'Literals':([4,],[7,]),'Ignore':([7,],[9,]),'Tokens':([9,],[12,]),'ListTokens':([18,23,],[20,25,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Gramatica","S'",1,None,None,None),
  ('Gramatica -> Lex','Gramatica',1,'p_gramatica','parser.py',5),
  ('Lex -> INIT PAL List','Lex',3,'p_lex','parser.py',8),
  ('List -> Literals Ignore Tokens','List',3,'p_list','parser.py',11),
  ('Literals -> INIT PAL = SIMB','Literals',4,'p_literals','parser.py',15),
  ('Ignore -> INIT PAL = SIMB','Ignore',4,'p_ignore','parser.py',18),
  ('Tokens -> INIT PAL = ListTokens','Tokens',4,'p_tokens','parser.py',22),
  ('ListTokens -> [ TOKEN ListTokens ]','ListTokens',4,'p_listtokens_with_value','parser.py',26),
  ('ListTokens -> , TOKEN','ListTokens',2,'p_listtokens_one','parser.py',30),
  ('ListTokens -> <empty>','ListTokens',0,'p_listtokens_empty','parser.py',34),
]
